[2018-08-26T15:38:15,358][FATAL][logstash.runner          ] An unexpected error occurred! {:error=>#<SystemCallError: Unknown error (SystemCallError) - <STDOUT>>, :backtrace=>["org/jruby/RubyIO.java:1457:in `write'", "org/jruby/RubyIO.java:1428:in `write'", "/home/ubuntu/elk/logstash-6.3.2/vendor/bundle/jruby/2.3.0/gems/logstash-output-stdout-3.1.4/lib/logstash/outputs/stdout.rb:43:in `block in multi_receive_encoded'", "org/jruby/RubyArray.java:1734:in `each'", "/home/ubuntu/elk/logstash-6.3.2/vendor/bundle/jruby/2.3.0/gems/logstash-output-stdout-3.1.4/lib/logstash/outputs/stdout.rb:42:in `multi_receive_encoded'", "/home/ubuntu/elk/logstash-6.3.2/logstash-core/lib/logstash/outputs/base.rb:89:in `multi_receive'", "org/logstash/config/ir/compiler/OutputStrategyExt.java:109:in `multi_receive'", "org/logstash/config/ir/compiler/OutputDelegatorExt.java:156:in `multi_receive'", "/home/ubuntu/elk/logstash-6.3.2/logstash-core/lib/logstash/pipeline.rb:475:in `block in output_batch'", "org/jruby/RubyHash.java:1343:in `each'", "/home/ubuntu/elk/logstash-6.3.2/logstash-core/lib/logstash/pipeline.rb:474:in `output_batch'", "/home/ubuntu/elk/logstash-6.3.2/logstash-core/lib/logstash/pipeline.rb:426:in `worker_loop'", "/home/ubuntu/elk/logstash-6.3.2/logstash-core/lib/logstash/pipeline.rb:384:in `block in start_workers'"]}
[2018-08-26T15:38:15,446][ERROR][org.logstash.Logstash    ] java.lang.IllegalStateException: Logstash stopped processing because of an error: (SystemExit) exit
